name    'cernops-glexecwn'
version '0.0.1'
author 'schwicke'
license 'Apache License, Version 2.0 (the "License")'
summary 'Glexec enabled Grid worker node for CERN'
description 'This modules provides classes and definitions required for a glExec enabled worker node with Argus'
project_page 'http://www.eu-emi.eu/'
dependency 'puppetlabs-stdlib', '>=4.1.0'
dependency 'cernops-fetchcrl', '>=0.0.2'
dependency 'puppetlabs-concat', '>=1.0.0'
dependency 'cernops-vosupport', '>=0.0.1'
